### PR TITLE
Code: Sign Up and Log In page

### PR DESCRIPTION
**Pull request by adithyark17**
added Sign up and Log in page for the Ecom Websit
Screenshot 2022-02-21 at 4 45 45 PM
e

### CODE REVIEW

**Comment by aliamaanansari** [comment]
Suggestion, for every html file create a separate folder and add index.html inside it, browser will automatically pick the index.html file, so the routes will look clean, instead of /pages/productlist.html it will look like /pages/productlist

**Review by tewarimohit — APPROVED** [review]
Just try to beautify css code a bit and remove unnecessary space.... otherwise good to merge

**Comment by anand-tiwari** [comment]
> ✔️ Deploy Preview for _vinylkart_ ready!
> 
> 🔨 Explore the source changes: [aed4231](https://github.com/adithyark17/VinylKart/commit/aed4231722977647e3c6a89c1378f0bec4e444ea)
> 
> 🔍 Inspect the deploy log: https://app.netlify.com/sites/vinylkart/deploys/621374983a524f000710af80
> 
> 😎 Browse the preview: https://deploy-preview-1--vinylkart.netlify.app

you can change netlify setting to deploy every branch, so we can preview ui along with  code

**Comment by anand-tiwari** [comment]
good to merge

**Review by anand-tiwari — APPROVED** [review]

**Pull request merged**
